# Keyword selection for Google Trends Data

1) University of British Columbia (UBC), Canada: Capstone Project
   - Title: Nowcasting Macroeconomic Indicators using Google Trends, 2022 
   - Keywords:
      - GDP category Keywords (141)
      - GDP keywords data from related queries (243)
      - GDP keywords data from related topics  (213)

2) Organisation for Economic Co-operation and Development (OECD): Working Papers, 2020

   - Title: OECD Economics Department Working Papers

   - Keywords:
     - GDP OECD Keywords (134)
    
3) Institute of Business Administration (IBA), Karachi, Pakistan:  Project Report
   - Title: Now casting GDP Growth and Forecasting Inflation of Pakistan
   - Keywords:
     - GDP IBA Keywords (58)

In [1]:
# import libraries/modules
import pandas as pd
from pytrends.request import TrendReq
import time
import json
startTime = time.time()

## Keywords from University of British Columbia (UBC): Capstone

### GDP category Keywords

In [83]:
capstone_cat = pd.read_csv('data/gdp_category_ts.csv', index_col=0)
capstone_cat.head()

,569,23,47,815,170,249,71,276,634,250,...,53,342,1159,1214,670,12,566,672,673,49
date,,,,,,,,,,,,,,,,,,,,,
2004-01-01,74,89,90,94,90,87,76,57,60,91,...,100,92,95,77,68,100,87,74,89,88
2004-02-01,70,86,88,93,88,87,71,58,51,98,...,96,99,95,90,78,99,96,78,81,100
2004-03-01,74,83,95,100,87,87,73,61,53,99,...,99,100,99,93,100,95,100,82,100,97
2004-04-01,72,82,92,96,89,82,70,55,53,95,...,90,95,89,98,97,94,87,78,81,89
2004-05-01,74,82,94,96,97,92,66,53,49,94,...,89,90,83,89,87,87,94,76,63,80

### Get column names

In [84]:
capstone_cat_col = capstone_cat.columns
capstone_cat_col

Index(['569', '23', '47', '815', '170', '249', '71', '276', '634', '250',
       ...
       '53', '342', '1159', '1214', '670', '12', '566', '672', '673', '49'],
      dtype='object', length=141)

### Convert to Dataframe

In [17]:
# convert cat_name to dataframe
df_capstone_cat = pd.DataFrame(capstone_cat_col, columns=['category'])
df_capstone_cat

    category
0        569
1         23
2         47
3        815
4        170
..       ...
136       12
137      566
138      672
139      673
140       49

[141 rows x 1 columns]

### Rename the column name

In [20]:
# rename the column
df_capstone_cat = df_capstone_cat.rename(columns={'category':'category_id'})
df_capstone_cat

    category_id
0           569
1            23
2            47
3           815
4           170
..          ...
136          12
137         566
138         672
139         673
140          49

[141 rows x 1 columns]

### Load Google Trends Category name from serpapi

- From: https://serpapi.com/google-trends-categories

In [86]:
gt_cat = pd.read_excel('data/GT_cat1.xlsx')
gt_cat.head()
gt_cat.shape

(1133, 2)

### Rename column name

In [22]:
# rename the column 
gt_cat = gt_cat.rename(columns={'cat':'category_id', 'Category':'category_name'})
gt_cat

      category_id                     category_name
0               0                    All categories
1               3              Arts & Entertainment
2             184  Celebrities & Entertainment News
3             316                Comics & Animation
4            1104                    Animated Films
...           ...                               ...
1128         1008                       Theme Parks
1129         1010        Travel Agencies & Services
1130         1392  Tourist Boards & Visitor Centers
1131         1019                   Vacation Offers
1132         1011       Travel Guides & Travelogues

[1133 rows x 2 columns]

### Get the category name

In [23]:
# Convert 'category_id' to int in both dataframes
df_capstone_cat['category_id'] = df_capstone_cat['category_id'].astype(int)
gt_cat['category_id'] = gt_cat['category_id'].astype(int)

# merge the dataframes
merged_df = df_capstone_cat.merge(gt_cat, on='category_id', how='left')

# Replace the 'category_name' in  dataframe
df_capstone_cat['category_name'] = merged_df['category_name']

df_capstone_cat

     category_id                     category_name
0            569                 Events & Listings
1             23                   Performing Arts
2             47                  Autos & Vehicles
3            815                    Vehicle Brands
4            170  Vehicle Licensing & Registration
..           ...                               ...
136           12             Business & Industrial
137          566              Textiles & Nonwovens
138          672              Coatings & Adhesives
139          673                   Dyes & Pigments
140           49                     Manufacturing

[141 rows x 2 columns]

### Check the missing values

In [24]:
missing_values_sum = df_capstone_cat.isnull().sum().sum()
print(missing_values_sum)

0

### Export the data to csv

In [15]:
# export the data to csv
df_capstone_cat.to_csv('data/category_name_capstone.csv')

### GDP keywords data from related queries

In [96]:

file1 = open('data/gdp_cat_queries_dict.json')
cat_queries_dict = json.load(file1)
cat_queries_dict.values()

dict_values([['cineplex', 'cinema'], ['dance', 'theatre'], ['honda', 'ford'], ['ford', 'honda'], ['license', 'driving'], ['blue cross', 'desjardins'], ['pizza pizza', 'pizza'], ['restaurant', 'restaurants'], ['clinic', 'dr'], ['hospital', 'hopital'], ['fire', 'emergency'], ['depression', 'anxiety'], ['home depot', 'ikea'], ['mls', 'real estate'], ['remax', 'real real'], ['kijiji', 'walmart'], ['hotel', 'air canada'], ['hotel', 'hotels'], ['google', 'apple'], ['shoes', 'boots'], ['xbox', 'videotron'], ['or', 'bijoux'], ['acces d', 'cra'], ['staples', 'desk'], ['bankruptcy', 'hollywoodpq'], ['credit', 'mortgage'], ['business', 'pret'], ['student', 'tuition'], ['mortgage', 'calculator'], ['lease', 'calculator'], ['farm', 'plant'], ['forest', 'forestry'], ['salmon', 'fish'], ['circulaire', 'iga'], ['cigarettes', 'smoke'], ['shoes', 'boots'], ['printing', 'vistaprint'], ['gas', 'gas prices'], ['bottle depot', 'plastic'], ['pharmacy', 'side effects'], ['hp', 'kingston'], ['generator', 'valve'], ['oscar', 'car wash'], ['google', 'mail'], ['java', 'windows'], ['rbc', 'td'], ['insurance', 'desjardins'], ['lawyer', 'law'], ['architecture', 'architects'], ['marketing', 'circulaire'], ['vet', 'animal hospital'], ['vacations', 'voyage'], ['acces', 'acces d'], ['canada', 'passport'], ['school', 'college'], ['clinic', 'dr'], ['chomage', 'assurance emploi'], ['nhl', 'hockey'], ['ordre', 'abstract'], ['hair removal', 'laser'], ['tractor', 'deere'], ['construction', 'doors'], ['clinique', 'clinique mÃ©dicale'], ['canada', 'tracking'], ['logistics', 'distribution'], ['jobs', 'job'], ['jobs', 'developer'], ['canning', 'kraft'], ['boat', 'kayak'], ['superstore', 'walmart'], ['trailers', 'trucks'], ['ship', 'traversier'], ['air', 'air france'], ['canada', 'customs'], ['rail', 'railway'], ['canada', 'tracking'], ['beer', 'lcbo'], ['doors', 'portail'], ['bridge', 'pont'], ['contractors', 'contracting'], ['home depot', 'paint'], ['netflix', 'dvd'], ['gift', 'birthday'], ['vacuum', 'appliances'], ['furniture', 'ikea'], ['garmin', 'gps'], ['hydro', 'gas'], ['auto', 'cars'], ['carpool', 'ride'], ['fifa', 'madden'], ['dog', 'pet'], ['yoga', 'fitness'], ['wedding', 'bridal'], ['car rental', 'taxi'], ['niagara falls', 'toronto'], ['rentals', 'cottage'], ['walmart', 'store'], ['garmin', 'gps'], ['fashion', 'louis vuitton'], ['truck', 'ford'], ['cruise', 'cruises'], ['backpack', 'luggage'], ['pizza pizza', 'pizza'], ['livres', 'librairie'], ['spa', 'massage'], ['theatre', 'macbeth'], ['emploi', 'quebec emploi'], ['resume', 'cover letter'], ['rent', 'for rent'], ['insurance', 'home insurance'], ['survival', 'economist'], ['finance', 'dow'], ['news', 'bbc'], ['election', 'election results'], ['toronto', 'news'], ['flooring', 'carpet'], ['pool', 'piscine'], ['td', 'monnex'], ['stock', 'tsx'], ['ttc', 'rrsp'], ['sql', 'access'], ['paypal', 'sql'], ['tax', 'tva'], ['omnivox', 'cegep'], ['git', 'github'], ['salesforce', 'crm'], ['expo', 'exhibition'], ['security', 'avg'], ['outsourcing', 'accenture'], ['server', 'servers'], ['cra', 'cra login'], ['godaddy', 'domain'], ['erp', 'dashboard'], ['management', 'project'], ['trailers', 'trucks'], ['homemade', 'potash'], ['acces d', 'canada post'], ['fabric fabric', 'fabric'], ['glue', 'epoxy'], ['couleur', 'couleurs'], ['covid', 'manufacturing']])

In [97]:
cat_queries_dict

{'569': ['cineplex', 'cinema'],
 '23': ['dance', 'theatre'],
 '47': ['honda', 'ford'],
 '815': ['ford', 'honda'],
 '170': ['license', 'driving'],
 '249': ['blue cross', 'desjardins'],
 '71': ['pizza pizza', 'pizza'],
 '276': ['restaurant', 'restaurants'],
 '634': ['clinic', 'dr'],
 '250': ['hospital', 'hopital'],
 '168': ['fire', 'emergency'],
 '437': ['depression', 'anxiety'],
 '11': ['home depot', 'ikea'],
 '29': ['mls', 'real estate'],
 '96': ['remax', 'real real'],
 '18': ['kijiji', 'walmart'],
 '67': ['hotel', 'air canada'],
 '179': ['hotel', 'hotels'],
 '5': ['google', 'apple'],
 '68': ['shoes', 'boots'],
 '78': ['xbox', 'videotron'],
 '696': ['or', 'bijoux'],
 '329': ['acces d', 'cra'],
 '95': ['staples', 'desk'],
 '423': ['bankruptcy', 'hollywoodpq'],
 '279': ['credit', 'mortgage'],
 '1160': ['business', 'pret'],
 '813': ['student', 'tuition'],
 '466': ['mortgage', 'calculator'],
 '468': ['lease', 'calculator'],
 '46': ['farm', 'plant'],
 '750': ['forest', 'forestry'],
 '747': ['salmon', 'fish'],
 '121': ['circulaire', 'iga'],
 '123': ['cigarettes', 'smoke'],
 '697': ['shoes', 'boots'],
 '1176': ['printing', 'vistaprint'],
 '1268': ['gas', 'gas prices'],
 '288': ['bottle depot', 'plastic'],
 '248': ['pharmacy', 'side effects'],
 '30': ['hp', 'kingston'],
 '287': ['generator', 'valve'],
 '612': ['oscar', 'car wash'],
 '13': ['google', 'mail'],
 '31': ['java', 'windows'],
 '7': ['rbc', 'td'],
 '38': ['insurance', 'desjardins'],
 '969': ['lawyer', 'law'],
 '477': ['architecture', 'architects'],
 '25': ['marketing', 'circulaire'],
 '380': ['vet', 'animal hospital'],
 '1010': ['vacations', 'voyage'],
 '726': ['acces', 'acces d'],
 '76': ['canada', 'passport'],
 '74': ['school', 'college'],
 '256': ['clinic', 'dr'],
 '508': ['chomage', 'assurance emploi'],
 '20': ['nhl', 'hockey'],
 '1199': ['ordre', 'abstract'],
 '144': ['hair removal', 'laser'],
 '748': ['tractor', 'deere'],
 '48': ['construction', 'doors'],
 '255': ['clinique', 'clinique mÃ©dicale'],
 '50': ['canada', 'tracking'],
 '664': ['logistics', 'distribution'],
 '60': ['jobs', 'job'],
 '802': ['jobs', 'developer'],
 '621': ['canning', 'kraft'],
 '1140': ['boat', 'kayak'],
 '841': ['superstore', 'walmart'],
 '289': ['trailers', 'trucks'],
 '665': ['ship', 'traversier'],
 '662': ['air', 'air france'],
 '354': ['canada', 'customs'],
 '666': ['rail', 'railway'],
 '1150': ['canada', 'tracking'],
 '277': ['beer', 'lcbo'],
 '650': ['doors', 'portail'],
 '651': ['bridge', 'pont'],
 '652': ['contractors', 'contracting'],
 '158': ['home depot', 'paint'],
 '1143': ['netflix', 'dvd'],
 '70': ['gift', 'birthday'],
 '271': ['vacuum', 'appliances'],
 '270': ['furniture', 'ikea'],
 '794': ['garmin', 'gps'],
 '233': ['hydro', 'gas'],
 '473': ['auto', 'cars'],
 '1339': ['carpool', 'ride'],
 '932': ['fifa', 'madden'],
 '882': ['dog', 'pet'],
 '94': ['yoga', 'fitness'],
 '293': ['wedding', 'bridal'],
 '205': ['car rental', 'taxi'],
 '208': ['niagara falls', 'toronto'],
 '1081': ['rentals', 'cottage'],
 '73': ['walmart', 'store'],
 '1188': ['garmin', 'gps'],
 '185': ['fashion', 'louis vuitton'],
 '610': ['truck', 'ford'],
 '206': ['cruise', 'cruises'],
 '1003': ['backpack', 'luggage'],
 '918': ['pizza pizza', 'pizza'],
 '355': ['livres', 'librairie'],
 '145': ['spa', 'massage'],
 '894': ['theatre', 'macbeth'],
 '960': ['emploi', 'quebec emploi'],
 '961': ['resume', 'cover letter'],
 '378': ['rent', 'for rent'],
 '465': ['insurance', 'home insurance'],
 '1164': ['survival', 'economist'],
 '784': ['finance', 'dow'],
 '1209': ['news', 'bbc'],
 '396': ['election', 'election results'],
 '408': ['toronto', 'news'],
 '832': ['flooring', 'carpet'],
 '952': ['pool', 'piscine'],
 '1139': ['td', 'monnex'],
 '107': ['stock', 'tsx'],
 '903': ['ttc', 'rrsp'],
 '343': ['sql', 'access'],
 '77': ['paypal', 'sql'],
 '278': ['tax', 'tva'],
 '1300': ['omnivox', 'cegep'],
 '730': ['git', 'github'],
 '341': ['salesforce', 'crm'],
 '334': ['expo', 'exhibition'],
 '314': ['security', 'avg'],
 '718': ['outsourcing', 'accenture'],
 '728': ['server', 'servers'],
 '1162': ['cra', 'cra login'],
 '53': ['godaddy', 'domain'],
 '342': ['erp', 'dashboard'],
 '1159': ['management', 'project'],
 '1214': ['trailers', 'trucks'],
 '670': ['homemade', 'potash'],
 '12': ['acces d', 'canada post'],
 '566': ['fabric fabric', 'fabric'],
 '672': ['glue', 'epoxy'],
 '673': ['couleur', 'couleurs'],
 '49': ['covid', 'manufacturing']}

### Get all the keywords and create a list

In [98]:
keywords_queries = [keyword for sublist in cat_queries_dict.values() for keyword in sublist]
len(keywords_queries)

282

### Remove duplicates from a list

In [99]:
keywords_queries = list(set(keywords_queries))
len(keywords_queries)

243

In [100]:
keywords_queries

['ship',
 'cover letter',
 'air canada',
 'godaddy',
 'project',
 'pharmacy',
 'gas',
 'logistics',
 'insurance',
 'homemade',
 'architects',
 'election results',
 'lawyer',
 'boat',
 'desjardins',
 'hotels',
 'hair removal',
 'finance',
 'netflix',
 'mortgage',
 'security',
 'rail',
 'cruise',
 'piscine',
 'covid',
 'staples',
 'glue',
 'or',
 'theatre',
 'job',
 'librairie',
 'potash',
 'cegep',
 'fashion',
 'domain',
 'birthday',
 'vet',
 'customs',
 'hospital',
 'fitness',
 'dashboard',
 'plastic',
 'plant',
 'ford',
 'doors',
 'oscar',
 'crm',
 'hockey',
 'dog',
 'couleur',
 'beer',
 'fabric',
 'trucks',
 'smoke',
 'architecture',
 'gift',
 'apple',
 'ordre',
 'air france',
 'hp',
 'dr',
 'vacations',
 'furniture',
 'yoga',
 'forest',
 'ttc',
 'anxiety',
 'mail',
 'madden',
 'fire',
 'trailers',
 'fish',
 'railway',
 'cra login',
 'hydro',
 'clinic',
 'toronto',
 'election',
 'tax',
 'cra',
 'windows',
 'home depot',
 'tractor',
 'car wash',
 'vacuum',
 'stock',
 'fifa',
 'chomage',
 'couleurs',
 'distribution',
 'jobs',
 'abstract',
 'tracking',
 'dow',
 'forestry',
 'avg',
 'gps',
 'canada post',
 'law',
 'outsourcing',
 'epoxy',
 'bbc',
 'tuition',
 'developer',
 'voyage',
 'salmon',
 'acces',
 'carpet',
 'resume',
 'rrsp',
 'pet',
 'rent',
 'paint',
 'massage',
 'marketing',
 'credit',
 'pizza pizza',
 'td',
 'portail',
 'niagara falls',
 'honda',
 'bijoux',
 'economist',
 'pizza',
 'restaurants',
 'monnex',
 'java',
 'macbeth',
 'dance',
 'appliances',
 'real real',
 'access',
 'home insurance',
 'management',
 'tva',
 'calculator',
 'contracting',
 'fabric fabric',
 'student',
 'iga',
 'backpack',
 'kayak',
 'git',
 'rbc',
 'hopital',
 'taxi',
 'emergency',
 'auto',
 'blue cross',
 'depression',
 'side effects',
 'wedding',
 'for rent',
 'cruises',
 'quebec emploi',
 'real estate',
 'ikea',
 'carpool',
 'expo',
 'bankruptcy',
 'remax',
 'survival',
 'xbox',
 'kingston',
 'car rental',
 'driving',
 'garmin',
 'kijiji',
 'pool',
 'lease',
 'school',
 'business',
 'air',
 'dvd',
 'tsx',
 'generator',
 'gas prices',
 'kraft',
 'canning',
 'omnivox',
 'deere',
 'accenture',
 'manufacturing',
 'traversier',
 'circulaire',
 'vistaprint',
 'contractors',
 'desk',
 'assurance emploi',
 'google',
 'clinique mÃ©dicale',
 'flooring',
 'cigarettes',
 'printing',
 'sql',
 'clinique',
 'louis vuitton',
 'spa',
 'boots',
 'erp',
 'license',
 'shoes',
 'restaurant',
 'store',
 'passport',
 'lcbo',
 'luggage',
 'servers',
 'acces d',
 'bridge',
 'pret',
 'bottle depot',
 'superstore',
 'cineplex',
 'emploi',
 'bridal',
 'livres',
 'github',
 'laser',
 'news',
 'paypal',
 'salesforce',
 'cars',
 'construction',
 'videotron',
 'farm',
 'college',
 'rentals',
 'ride',
 'exhibition',
 'cottage',
 'cinema',
 'hollywoodpq',
 'valve',
 'server',
 'hotel',
 'mls',
 'animal hospital',
 'canada',
 'truck',
 'walmart',
 'pont',
 'nhl']

### GDP keywords data from related topics

In [101]:
file2 = open('data/gdp_cat_topics_dict.json')
cat_topics_dict = json.load(file2)
cat_topics_dict.values()

dict_values([['Cineplex Entertainment', 'Film'], ['Dance', 'Theater'], ['Car', 'Canada'], ['Canada', 'Honda'], ['Driving', 'License'], ['Health', 'Insurance'], ['Recipe', 'Restaurant'], ['Restaurant', 'Menu'], ['Clinic', 'Walk-in clinic'], ['Hospital', 'Clinic'], ['Fire', 'Building insulation'], ['Disease', 'Anxiety'], ['Canada', 'The Home Depot'], ['Sales', 'House'], ['RE/MAX', 'Real Estate'], ['Canada', 'Kijiji'], ['Hotel', 'Flight'], ['Hotel', 'Toronto'], ['Download', 'Canada'], ['Canada', 'Shoes'], ['Xbox', 'Canada'], ['Jewellery', 'Volkswagen Group'], ['Canada Revenue Agency', 'Canada Customs and Revenue Agency'], ['Staples Canada', 'Staples'], ['Bankruptcy', 'HollywoodPQ'], ['Credit', 'Mortgage loan'], ['Business', 'Account'], ['Student', 'Scholarship'], ['Mortgage loan', 'Calculator'], ['Car', 'Lease'], ['Plant', 'Tree'], ['Forest', 'Tree'], ['Fish', 'Salmon'], ['Circulaire', 'Grocery store'], ['Cigarette', 'Cigars & Cigarillos'], ['Shoes', 'Boot'], ['Printing', 'Cimpress'], ['Price', 'Gasoline'], ['Canada', 'Plastic'], ['Jean Coutu Group', 'Side effect'], ['Hewlett-Packard', 'Laptop'], ['Valve', 'Electric generator'], ['Film', 'Academy Awards'], ['Google', 'Email'], ['Java', 'Microsoft Windows'], ['Royal Bank of Canada', 'Canada'], ['Insurance', 'Desjardins Group'], ['Lawyer', 'Law'], ['Architecture', 'Architect'], ['Marketing', 'Advertising'], ['Veterinarian', 'Dog'], ['Vacation', 'Expedia'], ['Desjardins Group', 'Facebook'], ['Canada', 'Passport'], ['University', 'School'], ['Clinic', 'Hospital'], ['Unemployment', 'Employment'], ['National Hockey League', 'NBA'], ['Quebec', 'Quebec City'], ['Hair', 'Shaving'], ['Tractor', 'John Deere'], ['Door', 'Canada'], ['Clinic', 'Clinique'], ['Canada Post', 'Shopping mall'], ['Logistics', 'Distribution'], ['Job', 'Employment'], ['Job', 'Software Developer'], ['Food', 'Canning'], ['Boat', 'Sales'], ['Flyer', 'Real Canadian Superstore'], ['Truck', 'Trailer'], ['Ship', 'Canada'], ['Airline', 'Air France'], ['Canada', 'Customs'], ['Train', 'Rail transport'], ['Canada Post', 'United Parcel Service'], ['Liquor Control Board of Ontario', 'Wine'], ['Door', 'Air conditioning'], ['Bridge', 'SNC-Lavalin'], ['General contractor', 'Bidding'], ['The Home Depot', 'Door'], ['Netflix', 'Film'], ['Gift', 'Flower'], ['Refrigerator', 'Canada'], ['Furniture', 'IKEA'], ['Garmin Ltd.', 'Global Positioning System'], ['Waste', 'Hydro-QuÃ©bec'], ['Car', 'Sales'], ['Carpool', 'Swimming pool'], ['FIFA', 'FIFA'], ['Dog', 'Veterinarian'], ['Yoga', 'Exercise'], ['Wedding', 'Dress'], ['Car', 'Rent'], ['Park', 'Niagara Falls'], ['Rent', 'Cottage'], ['Walmart', 'Walmart Canada'], ['Garmin Ltd.', 'Global Positioning System'], ['Model', 'Fashion'], ['Truck', 'Sales'], ['Cruise ship', 'Ferry'], ['Backpack', 'Baggage'], ['Menu', "McDonald's"], ['Book', 'Bookstore'], ['Massage', 'Spa'], ['Theatre', 'Theater'], ['Employment', 'Quebec City'], ['RÃ©sumÃ©', 'Letter'], ['Rent', 'Apartment'], ['Insurance', 'Home insurance'], ['Canada', 'Economy'], ['Stock', 'Price'], ['News', 'BBC News'], ['Election', 'Canada'], ['Newspaper', 'The Globe and Mail'], ['Flooring', 'Carpet'], ['Swimming pool', 'Swimming'], ['Bank', 'Insurance'], ['Stock', 'Price'], ['Toronto Transit Commission', 'ttc'], ['SQL', 'MySQL'], ['PayPal', 'Payment'], ['Tax', 'Canada Revenue Agency'], ['CEGEP', 'AutoCAD'], ['Git', 'GitHub'], ['Salesforce', 'Customer relationship management'], ['Trade fair', 'Toronto'], ['Antivirus software', 'AVG Technologies'], ['Outsourcing', 'Tax'], ['Server', 'FMyLife'], ['Canada Revenue Agency', 'Canada Customs and Revenue Agency'], ['GoDaddy', 'Domain name'], ['Enterprise resource planning', 'Dashboard'], ['Salary', 'Canada'], ['Truck', 'Trailer'], ['Fertilizer', 'Pesticide'], ['Canada', 'Canada Post'], ['Textile', 'Canada'], ['Adhesive', 'Paint'], ['Color', 'Dye'], ['Coronavirus disease 2019', 'Manufacturing']])

In [103]:
len(cat_topics_dict)

141

In [102]:
cat_topics_dict

{'569': ['Cineplex Entertainment', 'Film'],
 '23': ['Dance', 'Theater'],
 '47': ['Car', 'Canada'],
 '815': ['Canada', 'Honda'],
 '170': ['Driving', 'License'],
 '249': ['Health', 'Insurance'],
 '71': ['Recipe', 'Restaurant'],
 '276': ['Restaurant', 'Menu'],
 '634': ['Clinic', 'Walk-in clinic'],
 '250': ['Hospital', 'Clinic'],
 '168': ['Fire', 'Building insulation'],
 '437': ['Disease', 'Anxiety'],
 '11': ['Canada', 'The Home Depot'],
 '29': ['Sales', 'House'],
 '96': ['RE/MAX', 'Real Estate'],
 '18': ['Canada', 'Kijiji'],
 '67': ['Hotel', 'Flight'],
 '179': ['Hotel', 'Toronto'],
 '5': ['Download', 'Canada'],
 '68': ['Canada', 'Shoes'],
 '78': ['Xbox', 'Canada'],
 '696': ['Jewellery', 'Volkswagen Group'],
 '329': ['Canada Revenue Agency', 'Canada Customs and Revenue Agency'],
 '95': ['Staples Canada', 'Staples'],
 '423': ['Bankruptcy', 'HollywoodPQ'],
 '279': ['Credit', 'Mortgage loan'],
 '1160': ['Business', 'Account'],
 '813': ['Student', 'Scholarship'],
 '466': ['Mortgage loan', 'Calculator'],
 '468': ['Car', 'Lease'],
 '46': ['Plant', 'Tree'],
 '750': ['Forest', 'Tree'],
 '747': ['Fish', 'Salmon'],
 '121': ['Circulaire', 'Grocery store'],
 '123': ['Cigarette', 'Cigars & Cigarillos'],
 '697': ['Shoes', 'Boot'],
 '1176': ['Printing', 'Cimpress'],
 '1268': ['Price', 'Gasoline'],
 '288': ['Canada', 'Plastic'],
 '248': ['Jean Coutu Group', 'Side effect'],
 '30': ['Hewlett-Packard', 'Laptop'],
 '287': ['Valve', 'Electric generator'],
 '612': ['Film', 'Academy Awards'],
 '13': ['Google', 'Email'],
 '31': ['Java', 'Microsoft Windows'],
 '7': ['Royal Bank of Canada', 'Canada'],
 '38': ['Insurance', 'Desjardins Group'],
 '969': ['Lawyer', 'Law'],
 '477': ['Architecture', 'Architect'],
 '25': ['Marketing', 'Advertising'],
 '380': ['Veterinarian', 'Dog'],
 '1010': ['Vacation', 'Expedia'],
 '726': ['Desjardins Group', 'Facebook'],
 '76': ['Canada', 'Passport'],
 '74': ['University', 'School'],
 '256': ['Clinic', 'Hospital'],
 '508': ['Unemployment', 'Employment'],
 '20': ['National Hockey League', 'NBA'],
 '1199': ['Quebec', 'Quebec City'],
 '144': ['Hair', 'Shaving'],
 '748': ['Tractor', 'John Deere'],
 '48': ['Door', 'Canada'],
 '255': ['Clinic', 'Clinique'],
 '50': ['Canada Post', 'Shopping mall'],
 '664': ['Logistics', 'Distribution'],
 '60': ['Job', 'Employment'],
 '802': ['Job', 'Software Developer'],
 '621': ['Food', 'Canning'],
 '1140': ['Boat', 'Sales'],
 '841': ['Flyer', 'Real Canadian Superstore'],
 '289': ['Truck', 'Trailer'],
 '665': ['Ship', 'Canada'],
 '662': ['Airline', 'Air France'],
 '354': ['Canada', 'Customs'],
 '666': ['Train', 'Rail transport'],
 '1150': ['Canada Post', 'United Parcel Service'],
 '277': ['Liquor Control Board of Ontario', 'Wine'],
 '650': ['Door', 'Air conditioning'],
 '651': ['Bridge', 'SNC-Lavalin'],
 '652': ['General contractor', 'Bidding'],
 '158': ['The Home Depot', 'Door'],
 '1143': ['Netflix', 'Film'],
 '70': ['Gift', 'Flower'],
 '271': ['Refrigerator', 'Canada'],
 '270': ['Furniture', 'IKEA'],
 '794': ['Garmin Ltd.', 'Global Positioning System'],
 '233': ['Waste', 'Hydro-QuÃ©bec'],
 '473': ['Car', 'Sales'],
 '1339': ['Carpool', 'Swimming pool'],
 '932': ['FIFA', 'FIFA'],
 '882': ['Dog', 'Veterinarian'],
 '94': ['Yoga', 'Exercise'],
 '293': ['Wedding', 'Dress'],
 '205': ['Car', 'Rent'],
 '208': ['Park', 'Niagara Falls'],
 '1081': ['Rent', 'Cottage'],
 '73': ['Walmart', 'Walmart Canada'],
 '1188': ['Garmin Ltd.', 'Global Positioning System'],
 '185': ['Model', 'Fashion'],
 '610': ['Truck', 'Sales'],
 '206': ['Cruise ship', 'Ferry'],
 '1003': ['Backpack', 'Baggage'],
 '918': ['Menu', "McDonald's"],
 '355': ['Book', 'Bookstore'],
 '145': ['Massage', 'Spa'],
 '894': ['Theatre', 'Theater'],
 '960': ['Employment', 'Quebec City'],
 '961': ['RÃ©sumÃ©', 'Letter'],
 '378': ['Rent', 'Apartment'],
 '465': ['Insurance', 'Home insurance'],
 '1164': ['Canada', 'Economy'],
 '784': ['Stock', 'Price'],
 '1209': ['News', 'BBC News'],
 '396': ['Election', 'Canada'],
 '408': ['Newspaper', 'The Globe and Mail'],
 '832': ['Flooring', 'Carpet'],
 '952': ['Swimming pool', 'Swimming'],
 '1139': ['Bank', 'Insurance'],
 '107': ['Stock', 'Price'],
 '903': ['Toronto Transit Commission', 'ttc'],
 '343': ['SQL', 'MySQL'],
 '77': ['PayPal', 'Payment'],
 '278': ['Tax', 'Canada Revenue Agency'],
 '1300': ['CEGEP', 'AutoCAD'],
 '730': ['Git', 'GitHub'],
 '341': ['Salesforce', 'Customer relationship management'],
 '334': ['Trade fair', 'Toronto'],
 '314': ['Antivirus software', 'AVG Technologies'],
 '718': ['Outsourcing', 'Tax'],
 '728': ['Server', 'FMyLife'],
 '1162': ['Canada Revenue Agency', 'Canada Customs and Revenue Agency'],
 '53': ['GoDaddy', 'Domain name'],
 '342': ['Enterprise resource planning', 'Dashboard'],
 '1159': ['Salary', 'Canada'],
 '1214': ['Truck', 'Trailer'],
 '670': ['Fertilizer', 'Pesticide'],
 '12': ['Canada', 'Canada Post'],
 '566': ['Textile', 'Canada'],
 '672': ['Adhesive', 'Paint'],
 '673': ['Color', 'Dye'],
 '49': ['Coronavirus disease 2019', 'Manufacturing']}

### Get all the keywords and create a list

In [104]:
keywords_topics = [keyword for sublist in cat_topics_dict.values() for keyword in sublist]
len(keywords_topics)

282

### Remove duplicates from a list

In [106]:
keywords_topics = list(set(keywords_topics))
len(keywords_topics)

213

In [107]:
keywords_topics

['Canada Revenue Agency',
 'Niagara Falls',
 'Plant',
 'Unemployment',
 'Paint',
 'Book',
 'The Globe and Mail',
 'Mortgage loan',
 'License',
 'Theater',
 'Election',
 'Furniture',
 'Gasoline',
 'Lawyer',
 'Boat',
 'Shopping mall',
 'Forest',
 'Tax',
 'Fertilizer',
 'Anxiety',
 'Advertising',
 'Cigars & Cigarillos',
 'Kijiji',
 'FIFA',
 'Hospital',
 'Textile',
 'Walmart',
 'Carpet',
 'Facebook',
 'General contractor',
 'Ferry',
 'GitHub',
 'Payment',
 'Trailer',
 'Java',
 'Coronavirus disease 2019',
 'Bank',
 'Microsoft Windows',
 'Scholarship',
 'Bidding',
 'Newspaper',
 'Business',
 'Global Positioning System',
 'Toronto Transit Commission',
 'ttc',
 'Liquor Control Board of Ontario',
 'Domain name',
 'Credit',
 'SQL',
 'Toronto',
 'Adhesive',
 'Recipe',
 'Insurance',
 'Expedia',
 'Shaving',
 'Air conditioning',
 'Clinic',
 'Food',
 'Ship',
 'IKEA',
 'Flooring',
 'Jean Coutu Group',
 'Trade fair',
 'Real Estate',
 'Theatre',
 'Train',
 'Valve',
 'Employment',
 'Dashboard',
 'Walmart Canada',
 'Cigarette',
 'Manufacturing',
 'Door',
 'Cineplex Entertainment',
 'Dress',
 'National Hockey League',
 'Dog',
 'University',
 'Home insurance',
 'Lease',
 'Menu',
 'Cottage',
 'Laptop',
 'House',
 'Salesforce',
 'Desjardins Group',
 'AVG Technologies',
 'HollywoodPQ',
 'News',
 'Garmin Ltd.',
 'FMyLife',
 'Bankruptcy',
 'Dance',
 'Hotel',
 'Backpack',
 'Calculator',
 'Netflix',
 'Printing',
 'Building insulation',
 'Student',
 'Logistics',
 'Car',
 'Bookstore',
 'Antivirus software',
 'Wedding',
 'Health',
 'RE/MAX',
 'Side effect',
 'Baggage',
 'Staples',
 'Gift',
 'Park',
 'Law',
 'Massage',
 'Walk-in clinic',
 'Color',
 'Canada Customs and Revenue Agency',
 'Fish',
 'Yoga',
 'Real Canadian Superstore',
 'Dye',
 'Enterprise resource planning',
 'Refrigerator',
 'Wine',
 'Electric generator',
 'Royal Bank of Canada',
 'Vacation',
 'CEGEP',
 'Exercise',
 'Rail transport',
 'Tree',
 'Pesticide',
 'Price',
 'Jewellery',
 'The Home Depot',
 'Restaurant',
 'Canada Post',
 'Salmon',
 'Grocery store',
 'Git',
 'Server',
 'Apartment',
 'Quebec City',
 'Salary',
 'GoDaddy',
 'Clinique',
 "McDonald's",
 'Waste',
 'Swimming',
 'Letter',
 'BBC News',
 'MySQL',
 'Model',
 'Passport',
 'RÃ©sumÃ©',
 'Hydro-QuÃ©bec',
 'Job',
 'Rent',
 'Fashion',
 'Marketing',
 'Hair',
 'Canning',
 'Honda',
 'SNC-Lavalin',
 'AutoCAD',
 'Carpool',
 'Flower',
 'Bridge',
 'NBA',
 'Film',
 'Distribution',
 'Customer relationship management',
 'Circulaire',
 'Staples Canada',
 'Shoes',
 'Email',
 'School',
 'Quebec',
 'Sales',
 'Truck',
 'Airline',
 'United Parcel Service',
 'Flyer',
 'PayPal',
 'Plastic',
 'Economy',
 'Fire',
 'Disease',
 'Swimming pool',
 'Account',
 'Download',
 'Academy Awards',
 'Tractor',
 'Hewlett-Packard',
 'Customs',
 'Driving',
 'Stock',
 'Cimpress',
 'Spa',
 'Software Developer',
 'Veterinarian',
 'Outsourcing',
 'Boot',
 'Air France',
 'Architecture',
 'Cruise ship',
 'Google',
 'Volkswagen Group',
 'Canada',
 'Xbox',
 'John Deere',
 'Architect',
 'Flight']

## Keywords from Organisation for Economic Co-operation and Development (OECD)

In [108]:
oecd_key = pd.read_csv('data/OECD_keyword.csv')
oecd_key.head()

      category_name
0   Economic crisis
1            Crisis
2         Recession
3  Financial crisis
4             Krach

In [109]:
oecd_key.shape

(134, 1)

In [110]:
oecd_keywords = oecd_key["category_name"].values.tolist()
oecd_keywords

['Economic crisis',
 'Crisis',
 'Recession',
 'Financial crisis',
 'Krach',
 'Unemployment',
 'Unemployment benefits',
 'Welfare & Unemployment',
 'Food & Drink',
 'GPS & Navigation ',
 'Performing Arts             ',
 'Luggage topic',
 'Vehicle',
 'Brands',
 'Birthday',
 'Travel',
 'Energy & Utilities',
 'Vehicle Shopping',
 'Tobacco Products',
 'Health',
 'Pharmacy',
 'Carpooling & Ridesharing',
 'Sports',
 'Animal Products & Services',
 'Fitness',
 'Weddings',
 'Car',
 'Rental & Taxi Services',
 'Autos & Vehicles',
 'Tourist Destinations',
 'Home & Garden',
 'Events & Listings',
 'Grocery & Food Retailers',
 'Vehicle Licensing & Registration',
 'Timeshares & Vacation Properties',
 'Home',
 'Appliances',
 'Mass Merchants & Department Stores',
 'Car Electronics',
 'Fashion & Style',
 'Trucks & SUVs',
 'Home Furnishings',
 'Footwear',
 'Cruises & Charters',
 'Hotels & Accommodations',
 'Luggage & Travel',
 'Accessories',
 'Fast Food',
 'Book Retailers',
 'Veterinarians',
 'Spas & Beauty Services',
 'Acting & Theater',
 'Travel Agencies & Services',
 'Waiter',
 'Job Listings',
 'Resumes & Portfolios',
 'Jobs topic',
 'Temporary jobs',
 'Private employment',
 'agency',
 'Recruitement',
 'Developer Jobs',
 'Job search',
 'Bankruptcy topic',
 'Judicial Liquidation',
 'Bankruptcy',
 'Affordable housing',
 'House price index',
 'Apartments & Residential Rentals',
 'Insurance',
 'Home Improvement',
 'Economy News',
 'Business News',
 'World News',
 'Politics',
 'Newspapers',
 'Flooring',
 'Construction Consulting & Contracting',
 'Swimming Pools & Spas',
 'Civil',
 'Engineering',
 'Construction & Maintenance',
 'Investment',
 'Investing',
 'Financial Planning',
 'Data Management',
 'Enterprise Technology',
 'Accounting & Auditing',
 'CAD & CAM',
 'Development Tools',
 'Customer Relationship Management (CRM)',
 'Printing & Publishing         ',
 'Events',
 'Corporate',
 'Computer Security',
 'Outsourcing',
 'Distribution & Logistics',
 'Computer Servers',
 'Consulting',
 'Web Hosting & Domain Registration',
 'Enterprise Resource Planning (ERP)',
 'Business Operations',
 'Commercial Vehicles',
 'Agriculture & Forestry',
 'Agrochemicals',
 'Aviation',
 'Business & Industrial',
 'Chemicals Industry',
 'Textiles & Nonwovens',
 'Coatings & Adhesives',
 'Food Production',
 'Dyes & Pigments',
 'Freight & Trucking',
 'Transportation & Logistics',
 'Mail & Package Delivery',
 'Manufacturing',
 'Private employment agency',
 'House moving',
 'Recruitment',
 'Lawyer',
 'Jobs',
 'Public debt',
 'Office',
 'space',
 'Housing bubble',
 'Mortgage',
 'Loan',
 'Interest',
 'Student loan',
 'Bank',
 'Commercial Building',
 'Luggage',
 'Exportation',
 'Foreclosure']

In [111]:
len(oecd_keywords)

134

## Keywords from Institute of Business Administration (IBA), Karachi

In [87]:
df_cat_IBA = pd.read_excel('data/catagory_name_IBA.xlsx')
df_cat_IBA

       category_name
0    Economic crisis
1             Crisis
2          Recession
3   Financial crisis
4          Inflation
5       Unemployment
6               BISP
7     ehsaas program
8              USAID
9             Credit
10              Loan
11          Interest
12        House Loan
13          Car Loan
14              Food
15            Cinema
16              Cars
17          Birthday
18            Travel
19          Weddings
20           Fitness
21         Cigarette
22           Tourism
23            Hotels
24         Fast Food
25    House for sale
26      Construction
27        Investment
28              Jobs
29       Agriculture
30              FMCG
31          Aviation
32     Manufacturing
33           Textile
34      Economy News
35     Business News
36        World News
37          Politics
38        Newspapers
39           mehngai
40       Real estate
41           deficit
42         elections
43        parliament
44             taxes
45        government
46            budget
47   economic growth
48           subsidy
49   current account
50             trade
51           protest
52      stock market
53           revenue
54               LSM
55                M0
56               PSB
57               CPI

In [88]:
iba_category_name = df_cat_IBA["category_name"].values.tolist()
iba_category_name

['Economic crisis',
 'Crisis',
 'Recession',
 'Financial crisis',
 'Inflation',
 'Unemployment',
 'BISP',
 'ehsaas program',
 'USAID',
 'Credit',
 'Loan',
 'Interest',
 'House Loan',
 'Car Loan',
 'Food',
 'Cinema',
 'Cars',
 'Birthday',
 'Travel',
 'Weddings',
 'Fitness',
 'Cigarette',
 'Tourism',
 'Hotels',
 'Fast Food',
 'House for sale',
 'Construction',
 'Investment',
 'Jobs',
 'Agriculture',
 'FMCG',
 'Aviation',
 'Manufacturing',
 'Textile',
 'Economy News',
 'Business News',
 'World News',
 'Politics',
 'Newspapers',
 'mehngai',
 'Real estate',
 'deficit',
 'elections',
 'parliament',
 'taxes',
 'government',
 'budget',
 'economic growth',
 'subsidy',
 'current account',
 'trade',
 'protest',
 'stock market',
 'revenue',
 'LSM',
 'M0',
 'PSB',
 'CPI']

In [89]:
keywords = iba_category_name
len(keywords)

58